### ISSUE TITLE
Build failure

### ISSUE THREAD

**Issue by yesitsme007** [neozo-software/jblockchain#1]
Hi,
nice project! I tried to clone this project and build it with mvnw clean package. But I get one failing test:
```
Tests run: 4, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 0.031 sec <<< FAILURE! - in de.neozo.jblockchain.node.service.BlockServiceTests
addBlock_validHash(de.neozo.jblockchain.node.service.BlockServiceTests)  Time elapsed: 0.011 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertTrue(Assert.java:52)
	at de.neozo.jblockchain.node.service.BlockServiceTests.addBlock_validHash(BlockServiceTests.java:49)
```
Is this a problem of my setup or an error in the code?

**Comment by RolandColored** [comment]
I will try to reproduce this. What JDK version did you use?

**Comment by yesitsme007** [comment]
Hi Roland,
Thanks for looking into this. I have used Java version 8.1. I attach you the full log output. 
[jblockchain-build.log](https://github.com/neozo-software/jblockchain/files/3425251/jblockchain-build.log). Running on a Mac with latest maven (3.6.1).

I also tried to build with OpenJDK 11 (11.0.1). But this does not work because of missing dependencies, see [here](https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j)

After adding to `pom.xml`:
```
<dependency>
    <groupId>javax.xml.bind</groupId>
    <artifactId>jaxb-api</artifactId>
    <version>2.2.11</version>
</dependency>
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-core</artifactId>
    <version>2.2.11</version>
</dependency>
<dependency>
    <groupId>com.sun.xml.bind</groupId>
    <artifactId>jaxb-impl</artifactId>
    <version>2.2.11</version>
</dependency>
<dependency>
    <groupId>javax.activation</groupId>
    <artifactId>activation</artifactId>
    <version>1.1.1</version>
</dependency>
```

It fails with the same test:
```
Results :
Failed tests: 
  BlockServiceTests.addBlock_validHash:49 null
Tests run: 8, Failures: 1, Errors: 0, Skipped: 1
```

**Comment by RolandColored** [comment]
Finally found some spare time to tackle there issue. 😄 
I got the same error on my Mac with Java 8. But only when running the tests through maven and not one-by-one in IntelliJ. Then I found out, that the failing test will succeed, if I disable the long-running MiningServiceTest. Looks like it has some side effects which makes problems when running the tests in parallel (?) through maven.

Anyway, it should work now.
